version: "3.9"

services:
  app:
    container_name: "nimbbl_api"
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8888 --reload"
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    # depends_on:
    #   - db
    restart: always
    # networks:
    #   - host

  # db:
  #   container_name: "nimbbl_api_db"
  #   image: postgres:latest
  #   restart: always
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   env_file:
  #     - .env
  #   networks:
  #     - "nimbbl_api_network"

  # pgadmin:
  #   container_name: "nimbbl_api_pgadmin"
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   restart: always
  #   env_file:
  #     - .env
  #   networks:
  #     - "nimbbl_api_network"

# volumes:
#   postgres_data:


# networks:
#   nimbbl_api_network:
#     driver: bridge
